language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'

{% ifequal i.professor project.professor.id %}
                                                    {% ifequal i.ehCoordenador True %}
                                                        Coordenador: {{i.nome}}
                                                    {% else %}
                                                        Integrantes {{i.nome}}
                                                    {% endifequal %}
                                                {% endifequal %}
                                                {% ifequal i.ehCoordenador True %}
                                                        Coordenador: {{i.nome}}
                                                    {% else %}
                                                        Integrantes {{i.nome}}
                                                    {% endifequal %}